### ISSUE TITLE
Videos de Angular

### ISSUE THREAD

**Issue by aotaduy** [Frostqui/angular-espanol#1]
Hola tengo un blog con varios videos de angular que estoy haciendo para la catedra de la UTN de Rosario Argentina 
Te paso el link al tag donde los voy a ir agrupando, por ahora son mas basicos pero vamos a cubrir ruteo, unit test, y varios temas mas. 

Aca el link estaria muy bueno si lo podes agregar en tu lista 

https://aotaduy.github.io/area204/tags/#angular

Saludos!

**Comment by diegologs** [comment]
Hola, ¿puedes mandar pull request con los cambios en el repositorio? Muchas gracias :D

**Comment by aotaduy** [comment]
si no problem! gracias!

**Comment by diegologs** [comment]
Merged #2
